import { db } from '@services/firebase'; 
import { doc, setDoc, increment, serverTimestamp, collection } from 'firebase/firestore';

/**
 * Saves the exam result to the ledger. Universal for Exercises & Mock Tests.
 * ONLY updates global/lifetime stats if it's the first attempt to prevent farming.
 * * @param {string} userId - The student's Firebase UID.
 * @param {string} batchId - The current course batch.
 * @param {string} examId - The specific exam ID.
 * @param {Object} analyticsData - The payload generated by the analytics engine.
 * @param {boolean} isFirstAttempt - Prevents badge/XP/Stat farming.
 * @param {string} examType - "exercise" or "mock_test"
 */
export async function saveExamAndUnlockBadge(userId, batchId, examId, analyticsData, isFirstAttempt, examType = "exercise") {
  if (!userId || !analyticsData) return false;

  try {
    const userRef = doc(db, 'users', userId);
    const badgeId = analyticsData.badge.id;

    // 1. UPDATE LIFETIME USER PROFILE (ONLY IF FIRST ATTEMPT)
    if (isFirstAttempt) {
      const userUpdates = {
        badges: {
          [badgeId]: {
            count: increment(1),
            lastEarned: serverTimestamp(),
            name: analyticsData.badge.name,
            icon: analyticsData.badge.icon,
            desc: analyticsData.badge.desc
          }
        },
        lifetimeStats: {
          totalQuestionsAnswered: increment(analyticsData.overview.total),
          totalCorrect: increment(analyticsData.overview.score),
          totalPointsEarned: increment(analyticsData.overview.pointsEarned), // 🚨 NEW: Tracks points
          totalTimeSpentSec: increment(analyticsData.overview.totalTimeSec)
        }
      };

      // Isolate Mock Test Stats
      if (examType === "mock_test") {
        userUpdates.mockTestStats = {
          totalMockExamsTaken: increment(1),
          totalMockQuestions: increment(analyticsData.overview.total),
          totalMockCorrect: increment(analyticsData.overview.score),
          totalMockPoints: increment(analyticsData.overview.pointsEarned), // 🚨 NEW: Tracks points
          lastMockTimestamp: serverTimestamp()
        };
      }

      await setDoc(userRef, userUpdates, { merge: true });
    }

    // 2. CREATE A UNIQUE EXAM RECORD (The History Ledger)
    // Runs on EVERY attempt so the Line Chart can track progress
    const historyRef = doc(collection(db, `users/${userId}/exam_history`));
    
    await setDoc(historyRef, {
      examType: examType, 
      batchId: batchId || "general_practice",
      examId: examId || "unknown_exam",
      accuracy: analyticsData.overview.accuracyPercentage,
      score: analyticsData.overview.pointsEarned, // 🚨 Updated to save actual points
      correctAnswers: analyticsData.overview.score, // Keeps raw correct count
      earnedBadge: badgeId, 
      totalQuestions: analyticsData.overview.total,
      timeSpentSec: analyticsData.overview.totalTimeSec,
      isFirstAttempt: isFirstAttempt, 
      timestamp: serverTimestamp()
    });

    return true;
  } catch (error) {
    console.error("Failed to save analytics:", error);
    return false;
  }
}