// src/services/firebaseAnalytics.js
import { db } from '@services/firebase'; 
import { doc, setDoc, increment, serverTimestamp, collection } from 'firebase/firestore';

/**
 * Saves the exam result to the ledger. ONLY updates global stats if it's the first attempt.
 * @param {string} userId - The student's Firebase UID.
 * @param {string} batchId - The current course batch.
 * @param {string} examId - The specific exam ID.
 * @param {Object} analyticsData - The payload generated by generateExerciseAnalytics().
 * @param {boolean} isFirstAttempt - 🚨 NEW: Prevents badge/XP farming!
 */
export async function saveExamAndUnlockBadge(userId, batchId, examId, analyticsData, isFirstAttempt) {
  if (!userId || !analyticsData) return false;

  try {
    const userRef = doc(db, 'users', userId);
    const badgeId = analyticsData.badge.id;

    // 1. UPDATE USER PROFILE (ONLY IF FIRST ATTEMPT!)
    if (isFirstAttempt) {
      await setDoc(userRef, {
        badges: {
          [badgeId]: {
            count: increment(1),
            lastEarned: serverTimestamp(),
            name: analyticsData.badge.name,
            icon: analyticsData.badge.icon,
            desc: analyticsData.badge.desc
          }
        },
        lifetimeStats: {
          totalQuestionsAnswered: increment(analyticsData.overview.total),
          totalCorrect: increment(analyticsData.overview.score),
          totalTimeSpentSec: increment(analyticsData.overview.totalTimeSec)
        }
      }, { merge: true });
    }

    // 2. ALWAYS CREATE A UNIQUE EXAM RECORD (The Ledger)
    // We always save this so we can draw the "Progress Over Time" chart, 
    // even if it's their 10th time taking the quiz.
    const historyRef = doc(collection(db, `users/${userId}/exam_history`));
    
    await setDoc(historyRef, {
      examType: "exercise", // or "mock_test"
      batchId: batchId || "general_practice",
      examId: examId || "unknown_exam",
      accuracy: analyticsData.overview.accuracyPercentage,
      earnedBadge: badgeId, // We still record what behavior they showed today!
      score: analyticsData.overview.score,
      totalQuestions: analyticsData.overview.total,
      timeSpentSec: analyticsData.overview.totalTimeSec,
      isFirstAttempt: isFirstAttempt, // Good for future data science
      timestamp: serverTimestamp()
    });

    return true;
  } catch (error) {
    console.error("Failed to save analytics:", error);
    return false;
  }
}