// src/services/firebaseAnalytics.js
import { db } from '@services/firebase'; 
import { doc, setDoc, increment, serverTimestamp, collection } from 'firebase/firestore';

/**
 * Saves the exam result to the ledger. Universal for Exercises & Mock Tests.
 * ONLY updates global/lifetime stats if it's the first attempt to prevent farming.
 * * @param {string} userId - The student's Firebase UID.
 * @param {string} batchId - The current course batch.
 * @param {string} examId - The specific exam ID.
 * @param {Object} analyticsData - The payload generated by the engine.
 * @param {boolean} isFirstAttempt - Prevents badge/XP/Stat farming.
 * @param {string} examType - "exercise" or "mock_test" (Defaults to exercise)
 */
export async function saveExamAndUnlockBadge(userId, batchId, examId, analyticsData, isFirstAttempt, examType = "exercise") {
  if (!userId || !analyticsData) return false;

  try {
    const userRef = doc(db, 'users', userId);
    const badgeId = analyticsData.badge.id;

    // 1. UPDATE USER PROFILE (ONLY IF FIRST ATTEMPT!)
    if (isFirstAttempt) {
      // Define the base updates that happen for EVERYTHING
      const userUpdates = {
        badges: {
          [badgeId]: {
            count: increment(1),
            lastEarned: serverTimestamp(),
            name: analyticsData.badge.name,
            icon: analyticsData.badge.icon,
            desc: analyticsData.badge.desc
          }
        },
        lifetimeStats: {
          totalQuestionsAnswered: increment(analyticsData.overview.total),
          totalCorrect: increment(analyticsData.overview.score),
          totalTimeSpentSec: increment(analyticsData.overview.totalTimeSec)
        }
      };

      // 🚨 THE PRO TIP: Create a separate bucket specifically for Mock Test performance
      if (examType === "mock_test") {
        userUpdates.mockTestStats = {
          totalMockExamsTaken: increment(1),
          totalMockQuestions: increment(analyticsData.overview.total),
          totalMockCorrect: increment(analyticsData.overview.score),
          lastMockTimestamp: serverTimestamp()
        };
      }

      // Execute the merge update
      await setDoc(userRef, userUpdates, { merge: true });
    }

    // 2. ALWAYS CREATE A UNIQUE EXAM RECORD (The Ledger)
    // This allows us to see the student's progress history over time.
    const historyRef = doc(collection(db, `users/${userId}/exam_history`));
    
    await setDoc(historyRef, {
      examType: examType, // "exercise" or "mock_test"
      batchId: batchId || "general_practice",
      examId: examId || "unknown_exam",
      accuracy: analyticsData.overview.accuracyPercentage,
      earnedBadge: badgeId, 
      score: analyticsData.overview.score,
      totalQuestions: analyticsData.overview.total,
      timeSpentSec: analyticsData.overview.totalTimeSec,
      isFirstAttempt: isFirstAttempt, 
      timestamp: serverTimestamp()
    });

    return true;
  } catch (error) {
    console.error("Failed to save analytics:", error);
    return false;
  }
}